account/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from account.views import MainLoginView,RegisterView,AdvisorView,SeekerView,ProfileView

app_name = 'account'

urlpatterns = [
    path('login/', MainLoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('register-advisor/', AdvisorView.as_view(), name='advisor'),
    path('register-seeker/', SeekerView.as_view(), name='seeker'),
    path('profile/<slug:slug>', ProfileView.as_view(), name='profile'),
    path('log-out', LogoutView.as_view(), name='log-out'),
]

core/urls.py
from django.urls import path

from .views import (
    HomePageView,
    CongratulationsPageView,
    MessageCongratulationsPageView,
    MatchedView,
    MessageAdvisorView
)

app_name = 'core'


urlpatterns = [
    path("", HomePageView.as_view(), name="index"),
    path("congratulations/", CongratulationsPageView.as_view(), name="congratulations"),
    path("message-congratulations/", MessageCongratulationsPageView.as_view(), name="message-congratulations"),
    path("matched-advisors/", MatchedView.as_view(), name="matched-advisors"),
    path("message-advisor/<slug:slug>", MessageAdvisorView.as_view(), name="message-advisor"),
]

fibility/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('account.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models


class AboutUsText(models.Model):
    text = models.TextField()
    added_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.text}'

    class Meta:
        verbose_name = 'About us text'
        verbose_name_plural = 'About us texts'

class MoreOnUsText(models.Model):
    text = models.TextField()
    added_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.text}'

    class Meta:
        verbose_name = 'More on us text'
        verbose_name_plural = 'More on us texts'

core/forms.py
from django import forms
from account.models import Message

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['subject', 'text']

        widgets = {
            'subject': forms.TextInput(attrs={'id': 'subject', 'placeholder': 'Your Subject', 'class': 'form-control'}),
            'text': forms.Textarea(attrs={'id': 'message', 'placeholder': 'Your Message', 'class': 'form-control', 'cols':'65', 'rows': '10'}),
        }

core/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView, DetailView
from .models import AboutUsText, MoreOnUsText
from account.models import User
from django.views.generic.edit import FormMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .forms import MessageForm

class HomePageView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['aboutus'] = AboutUsText.objects.order_by('-id').first
        context['moreonus'] = MoreOnUsText.objects.order_by('-id').first
        return context

class MatchedView(ListView):
    model = User
    context_object_name = "matched_advisors"
    template_name = "table.html"
    queryset = User.objects.filter(is_advisor=True).order_by('-id')[:1]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    # def get_queryset(self):
        
    #     print(queryset)

    #     return queryset

class MessageAdvisorView(FormMixin, DetailView):
    model = User
    context_object_name = "advisor"
    template_name = "message.html"
    form_class = MessageForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get_success_url(self):
        return reverse_lazy('core:message-congratulations')

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.sender = self.request.user
        form.instance.receiver = self.get_object()
        form.save()
        return super().form_valid(form)


class CongratulationsPageView(TemplateView):
    template_name = 'congratulation.html'


class MessageCongratulationsPageView(TemplateView):
    template_name = 'mcongratulation.html'

core/templates/includes/footer.html
<footer style="display: block !important;">
    <div style="display: flex; max-width: 1120px; justify-content: space-between; margin: 0 auto;">
      <div>
        <ul class="footer-list">
          <li> <a href="#">About Us</a> </li>
          <li> <a href="#">More on us</a> </li>
          <li> <a href="#">How it works</a> </li>
        </ul>
      </div>
      <div>
        <p id="all-rights">© All Rights 2021</p>
      </div>
    </div>

  </footer>

core/templates/includes/header.html
{% load static %}
{% load static %}
<header>
    <nav class="navbar">
      <div class="navbrand">
        <a style="display: inline;" href="{% url 'core:index' %}"><img class="logo"
            src="{% static 'images/logo.png' %}" alt="Logo"></a>
        <div class="burger" id="burger">
          <span class="burger-open">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="16">
              <g fill="#252a32" fill-rule="evenodd">
                <path d="M0 0h24v2H0zM0 7h24v2H0zM0 14h24v2H0z" />
              </g>
            </svg>
          </span>
          <span class="burger-close">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20">
              <path fill="#252a32" fill-rule="evenodd"
                d="M17.778.808l1.414 1.414L11.414 10l7.778 7.778-1.414 1.414L10 11.414l-7.778 7.778-1.414-1.414L8.586 10 .808 2.222 2.222.808 10 8.586 17.778.808z" />
            </svg>
          </span>
        </div>
      </div>
      <div>
        <ul class="menu" id="menu">
          <li class="menu-item"><a href="#about-us" class="menu-link">About</a></li>
          <li class="menu-item"><a href="#time-l" class="menu-link">How it works</a></li>
          <li class="menu-item"><a href="#moreonus" class="menu-link">Our why </a></li>
          {% if request.user.is_authenticated %}
          <div class="first">
            <a href="{% url 'account:profile' request.user.slug%}">
            <button class="profile-img"><img width="24px" height="24px" style="margin-right: 11px;"
                    src="{% static 'images/user.png' %}" alt="">{{ request.user.full_name }}</button>
                </a>
        </div>
        {% else %}
          <li class="menu-item first"><a href="{% url 'account:login' %}" style="color: #162C9B;" class="menu-link">Sign in</a></li>
          <li class="menu-item first"><a style="padding-left: 15px!important;" href="{% url 'account:register' %}"
              class="signup">Sign up</a></li>
              {% endif %}
        </ul>
      </div>

      <div class="second">
        {% if request.user.is_authenticated %}
        <div>
          <a href="{% url 'account:profile' request.user.slug%}">
          <button class="profile-img"><img width="24px" height="24px" style="margin-right: 11px;"
                  src="{% static 'images/user.png' %}" alt="">{{ request.user.full_name }}</button>
              </a>
      </div>
        {% else %}
        <a class="sign" href="{% url 'account:login' %}">Sign in</a>
        <a class="signup" href="{% url 'account:register' %}">Sign up</a>
      {% endif %}

      </div>
    </nav>
    </nav>

  </header>