account/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from account.views import MainLoginView,RegisterView,AdvisorView,SeekerView,ProfileView

app_name = 'account'

urlpatterns = [
    path('login/', MainLoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('register-advisor/', AdvisorView.as_view(), name='advisor'),
    path('register-seeker/', SeekerView.as_view(), name='seeker'),
    path('profile/<slug:slug>', ProfileView.as_view(), name='profile'),
    path('log-out', LogoutView.as_view(), name='log-out'),
]

core/urls.py
from django.urls import path

from .views import (
    HomePageView,
    CongratulationsPageView,
    MessageCongratulationsPageView,
    MatchedView,
    MessageAdvisorView
)

app_name = 'core'


urlpatterns = [
    path("", HomePageView.as_view(), name="index"),
    path("congratulations/", CongratulationsPageView.as_view(), name="congratulations"),
    path("message-congratulations/", MessageCongratulationsPageView.as_view(), name="message-congratulations"),
    path("matched-advisors/", MatchedView.as_view(), name="matched-advisors"),
    path("message-advisor/<slug:slug>", MessageAdvisorView.as_view(), name="message-advisor"),
]

fibility/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('account.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager, UnicodeUsernameValidator
from .common import slugify
from .managers import UserManager
from django.core.mail import send_mail

from django.contrib.auth.base_user import BaseUserManager
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):
    username_validator = UnicodeUsernameValidator
    username = models.CharField(
        ('username'),
        max_length=150,
        blank=True,
        null=True,
        unique=False,
        help_text=('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': ("A user with that username already exists."),
        },
    )
    email = models.EmailField(('email adress'), unique=True)
    full_name = models.CharField(max_length=100)
    age = models.IntegerField(null=True, blank=True)
    number = models.CharField(max_length=100, null=True, blank=True)
    profile_pic = models.ImageField(upload_to='images', null=True, blank=True)
    is_advisor = models.BooleanField(default=False)
    is_seeker = models.BooleanField(default=False)
    slug = models.SlugField(max_length=255, null=True, blank=True)
    state = models.ForeignKey("State", on_delete=models.CASCADE, db_index=True, related_name='message', null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def save(self, *args, **kwargs):
        super(User, self).save(*args, **kwargs)
        self.slug = f'{slugify(self.full_name)}-{self.id}'
        super(User, self).save(*args, **kwargs)

class Message(models.Model):
    subject = models.CharField(max_length=100)
    text = models.TextField()
    sender = models.ForeignKey(User, on_delete=models.CASCADE, db_index=True, related_name='message')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, db_index=True, related_name='themessage')

    class Meta:
        verbose_name = 'Message'
        verbose_name_plural = 'Messages'

    def __str__(self):
        return f'{self.subject}'

    def save(self, *args, **kwargs):
        super(Message, self).save(*args, **kwargs)
        print(self.subject, self.text, self.sender.email, self.receiver.email)
        send_mail(self.subject, f'from {self.sender.email} \n {self.text}', self.sender.email, [self.receiver.email,])
        super(Message, self).save(*args, **kwargs)

class State(models.Model):
    title = models.CharField(max_length=255, null=True)
    added_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'State'
        verbose_name_plural = 'States'

# class StartBudget(models.Model):
#     budget = models.IntegerField(null=True)
#     added_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)

#     def __str__(self):
#         return f'{self.budget}'

#     class Meta:
#         verbose_name = 'Start Budget'
#         verbose_name_plural = 'Start Budgets'

# class EndBudget(models.Model):
#     budget = models.IntegerField(null=True)
#     added_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)

#     def __str__(self):
#         return f'{self.budget}'

#     class Meta:
#         verbose_name = 'End Budget'
#         verbose_name_plural = 'End Budgets'

# class TypeOfAdvice(models.Model):
#     title = models.CharField(max_length=255, null=True)
#     added_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)

#     def __str__(self):
#         return f'{self.title}'

#     class Meta:
#         verbose_name = 'Type of Advice'
#         verbose_name_plural = 'Types of Advices'

account/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordResetForm, SetPasswordForm,UsernameField
from .models import User
from django_range_slider.fields import RangeSliderField


class AdvisorRegisterForm(UserCreationForm):
    # salary = RangeSliderField(minimum=0,maximum=100000,step=1)

    password1 = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'placeholder' : 'password',
                'class' : 'form-control',
            }))

    password2 = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'placeholder' : 'confirm password',
                'class' : 'form-control',
            }))
        
    profile_pic = forms.FileField(
        widget = forms.FileInput(
            attrs={
                'id': "nopic"
            }), required=False)

    class Meta:
        model = User
        fields = ('full_name','email','password1','password2', 'number', 'is_advisor', 'profile_pic', 'state')

        widgets = {
            'full_name': forms.TextInput(attrs={'id': 'fullname', 'placeholder': 'Full Name', 'class': 'form-control'}),
            'state': forms.Select(attrs={'id': 'sell', 'class': 'form-control select__field'}),
            # 'type_of_advice': forms.Select(attrs={'id': 'sell', 'class': 'form-control select__field'}),
            'email': forms.EmailInput(attrs={'id': 'email', 'placeholder': 'name@gmail.com', 'class': 'form-control'}),
            'is_employed': forms.CheckboxInput(attrs={'id': 'is_employed'}),
            'is_advisor': forms.CheckboxInput(attrs={'id': 'is_advisor', 'checked':'True'}),
            'number': forms.NumberInput(attrs={'id': 'phone', 'placeholder': '012-345-6789', 'class': 'form-control', 'pattern': '[0-9]{3}-[0-9]{2}-[0-9]{3}'}),
            # 'company': forms.TextInput(attrs={'id': 'company', 'placeholder': 'company', 'class': 'form-control'}),
        }

class SeekerRegisterForm(UserCreationForm):
    # salary = RangeSliderField(minimum=0,maximum=100000,step=1)

    password1 = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'placeholder' : 'password',
                'class' : 'form-control',
            }))

    password2 = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'placeholder' : 'confirm password',
                'class' : 'form-control',
            }))

    class Meta:
        model = User
        fields = ('full_name','email','password1','password2', 'number', 'is_seeker', 'profile_pic', 'age', 'state')

        widgets = {
            'full_name': forms.TextInput(attrs={'id': 'fullname', 'placeholder': 'Full Name', 'class': 'form-control'}),
            'state': forms.Select(attrs={'id': 'sell', 'placeholder': 'Username', 'class': 'form-control select__field'}),
            # 'type_of_advice': forms.Select(attrs={'id': 'sell', 'class': 'form-control select__field'}),
            'email': forms.EmailInput(attrs={'id': 'email', 'placeholder': 'name@gmail.com', 'class': 'form-control'}),
            'is_seeker': forms.CheckboxInput(attrs={'id': 'is_seeker', 'checked': 'True'}),
            'age': forms.NumberInput(attrs={'id': 'number', 'placeholder': 'Age', 'class': 'form-control'}),
            'number': forms.NumberInput(attrs={'id': 'phone', 'placeholder': '123-456-7890', 'class': 'form-control', 'pattern': '[0-9]{3}-[0-9]{2}-[0-9]{3}'}),
            
            # 'company': forms.TextInput(attrs={'id': 'company', 'placeholder': 'company', 'class': 'form-control'}),
        }


class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={
        'autofocus': True,
        'class': 'form-control',
        'placeholder': 'Email',
        'name': 'email'
    }))
    password = forms.CharField(
        label=("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'current-password',
            'class': 'form-control',
            'name': 'password',
            'placeholder': 'Password'
        }),
    )

    class Meta:
        model = User
        fields = ['username', 'password']


class UpdateProfileForm(forms.ModelForm):

    profile_pic = forms.FileField(
        widget = forms.FileInput(
            attrs={
                'id': "nopic"
            }), required=False)

    class Meta:
        model = User
        fields = ['full_name', 'email', 'number', 'profile_pic', 'state']

        widgets = {
            'full_name': forms.TextInput(attrs={'id': 'full_name', 'placeholder': 'First Name',  'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'id': 'email', 'placeholder': 'Bio',  'class': 'form-control'}),
            'state': forms.Select(attrs={'id': 'sell', 'placeholder': 'Username', 'class': 'form-control select__field'}),
            # 'company': forms.TextInput(attrs={'id': 'company', 'placeholder': 'company', 'class': 'form-control'}),
            'number': forms.NumberInput(attrs={'id': 'phone', 'placeholder': '123-456-7890', 'class': 'form-control', 'pattern': '[0-9]{3}-[0-9]{2}-[0-9]{3}'}),
        }

account/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DetailView, TemplateView, UpdateView
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView
from account.models import User
from account.forms import LoginForm, AdvisorRegisterForm, SeekerRegisterForm, UpdateProfileForm
from django.core.exceptions import PermissionDenied

class MainLoginView(LoginView):
    template_name = 'signin.html'
    form_class = LoginForm

class RegisterView(TemplateView):
    template_name = 'registration.html'

class AdvisorView(CreateView):
    model = User
    template_name = 'financial-advisor.html'
    form_class = AdvisorRegisterForm
    success_url = reverse_lazy('core:congratulations')

    def form_valid(self, form):
        form.instance.is_advisor = True
        form.save()
        return super().form_valid(form)

class SeekerView(CreateView):
    model = User
    template_name = 'advice-seekers.html'
    form_class = SeekerRegisterForm
    success_url = reverse_lazy('core:congratulations')

    def form_valid(self, form):
        form.instance.is_seeker = True
        form.save()
        return super().form_valid(form)    

class ProfileView(UpdateView):
    model = User
    template_name = 'profile.html'
    form_class = UpdateProfileForm
    success_url = reverse_lazy('core:index')

    # def get_success_url(self):
    #     return reverse_lazy('accounts:user-profile', kwargs={'pk':self.get_object().pk})

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.username != self.get_object().username:
            raise PermissionDenied
        return super(ProfileView, self).dispatch(request, *args, **kwargs)

account/templates/advice-seekers.html
{% extends 'base2.html' %}
{% load static %}
{% block title %} Advice Seekers {% endblock %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}">
<link rel="stylesheet" href="{% static 'css/advice-seekers.css' %}">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">

<style>
  .field{
    display: flex;
    flex-wrap: nowrap;
  }
  footer {
    margin-top: 600px;
  }
  .numb-1 {
    margin: 20px;

    float: left;
  }

  #usa {
    float: left;
    margin: 20px;
  }

  input[type="tel"] {
    width: 70%;
  }

  input[type="range"]:focus {
    border: none;
  }

  .yes-no-radio-title {
    margin-bottom: 5px;

  }

  .radio-btns-option {
    display: inline-block;
    float: left;
    margin: 0;
    padding: 0;
    font-size: 1em;
  }

  input[type="radio"] {
    position: absolute;
    left: -9000px;
  }

  input[type="radio"]:checked+.radio-label {
    background: #d9d9d9;
    color: #fff;
  }

  .radio-label {
    display: inline-block;
    border: 2px solid #d9d9d9;
    border-right: none;
    padding: 8px 30px;
    margin: 0;
    cursor: pointer;
  }

  .right {
    right: -63px;
  }

  .radio-label:hover {
    background: #d9d9d9;
    color: #fff;
  }

  .radio-btns-option:first-of-type .radio-label {}

  .radio-btns-option:nth-of-type(2n) .radio-label {
    border-right: 2px solid #d9d9d9;

  }

  input[type="range"] {
    -webkit-appearance: none;
    -moz-appearance: none;
    width: 300px;
    height: 10px;
    padding: 0;
    outline: none;
    cursor: pointer;
  }


  /*Chrome thumb*/

  input[type="range"]::-webkit-slider-thumb {
    -webkit-appearance: none;
    -moz-appearance: none;
    /*16x16px adjusted to be same as 14x14px on moz*/
    height: 22px;
    width: 18px;
    background: #162c9b;
    border: none;
  }


  /*Mozilla thumb*/

  input[type="range"]::-moz-range-thumb {
    -webkit-appearance: none;
    -moz-appearance: none;
    height: 22px;
    width: 18px;
  }

  /* range input{
  -webkit-appearance: none;
  width: 100%;
  height: 9px;
  background: #ddd;
  outline: none;
  border: none;
  z-index: 2222;
}
.range input::-webkit-slider-thumb{
  -webkit-appearance: none;
  appearance: none;
  width: 25px;
  height: 25px;
  background: #162c9b;
  cursor: pointer;
}
.range input::-moz-range-thumb{
  -webkit-appearance: none;
  appearance: none;
  width: 25px;
  height: 25px;
  background: #162c9b;
  cursor: pointer;
}
input[type=range] {
      -webkit-appearance: none;
      -moz-apperance: none;
      height: 9px;

      background-image: -webkit-gradient(linear,
          left top, 
          right top, 
          color-stop(60%, #ff5126),
          color-stop(60%, #eeeeee));

      background-image: -moz-linear-gradient(left center,
          #ff5126 0%, #ff5126 60%,
          #eeeeee 60%, #eeeeee 100%);
  }
.range input::-webkit-progress-value {
  background: #ff6e4a; 
  content: '';
  pointer-events: none;
} */
</style>
{% endblock %}


{% block content %}

<section id="cover" class="min-vh-100">
  <div id="cover-caption">
    <div class="container">
      <div class="row text-white">
        <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4">
          <h1 class="display-4 py-2 " style="color: black;
          font-weight: 400;
          font-size: 50px;">Advice Seekers</h1>
          <div class="px-2">
            <form method="POST" class="my-login-validation" novalidate="" enctype="multipart/form-data" action="">
              {% csrf_token %}
              {{form.non_field_error}}

              <div class="form-group">
                <label for="email">E-Mail </label>
                {{form.email}}
                {{form.email.errors}}
                <div class="invalid-feedback">
                  Your email is invalid
                </div>
              </div>

              <div class="form-group">
                <label for="password">Password</label>
                {{form.password1}}
                {{form.password1.errors}}
                <div class="invalid-feedback">
                  Password is required
                </div>
              </div>

              <div class="form-group">
                <label for="password">Password</label>
                  {{form.password2}}
                  {{form.password2.errors}}
                <div class="invalid-feedback">
                  Password is required
                </div>
              </div>

              <div class="form-group">
                <label for="fullname">Full Name*</label>
                {{form.full_name}}
                {{form.full_name.errors}}
                <div class="invalid-feedback">
                  Your fullname is invalid
                </div>
              </div>

              
              <div class="form-group">
                <label for="age">Age</label>
                {{form.age}}
                {{form.age.errors}}
                <div class="invalid-feedback">
                  Age is required
                </div>
              </div>

              <div class="state"><label for="sel1">State*</label>
                {{form.state}}
                {{form.state.errors}}


            </div>
              <br>
              </div>


              <div class="form-group">
                <label for="phone">Enter your phone number:</label> <br>
  <img id="usa" src="{% static 'images/US.png' %}" alt="USA">
  <p class="numb-1">+1 </p> 
                  {{form.number}}
                  {{form.number.errors}}
              </div>
              <div class="form-group d-none" id="buttons">
                <p style="color: #595959;">Profile Picture</p> <span class=" btn btn-primary btn-file upload">
                  Add photo
                  {{form.profile_pic}}
                  {{form.profile_pic.errors}}

                </span>
                <a href="" class="btn" id="delete" style="color: white;"> Delete</a>

              </div>

              <div class="form-group m-0">
                <input type="submit" value="Save" class="save-btn btn  btn-primary btn-block">
              </div>

            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>




{% endblock %}

{% block js %}

<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/8.4.7/js/intlTelInput.js"></script>

<script>
  //       $("input[type=range]").mousemove(function (e) {
  //     var val = ($(this).val() - $(this).attr('min')) / ($(this).attr('max') - $(this).attr('min'));
  //     var percent = val * 100;

  //     $(this).css('background-image',
  //         '-webkit-gradient(linear, left top, right top, ' +
  //         'color-stop(' + percent + '%, #ff5126), ' +
  //         'color-stop(' + percent + '%, #eeeeee)' +
  //         ')');

  //     $(this).css('background-image',
  //         '-moz-linear-gradient(left center, #ff5126 0%, #ff5126 ' + percent + '%, #eeeeee ' + percent + '%, #eeeeee 100%)');
  // }); 

  var slider = document.getElementById("myRange");
  var output = document.getElementById("demo");
  output.innerHTML = slider.value;

  slider.oninput = function () {
    output.innerHTML = this.value;
  }


</script>
{% endblock %}

account/templates/profile.html
{% extends 'base2.html' %}
{% load static %}

{% block title %} Profile {% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
    integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w=="
    crossorigin="anonymous" />
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
<style>
</style>
{% endblock %}

{% block content %}
<section id="cover" class="min-vh-100" style="margin-bottom: 300px;">
    <div id="cover-caption">
      <div class="container">
        <div class="row text-white">
          <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4" style="max-width: 743px;">
            <h1 class="display-4 py-2 text-truncate" style="color: black;
            font-weight: 400;
            font-size: 55px;">Profile</h1>
            <div class="px-2">
                <form method="POST" class="my-login-validation" novalidate="" action=""
                            enctype="multipart/form-data">
                            {% csrf_token %}
                            {{form.non_field_error}}

                            <div class="form-group">
                                <label for="email" style="color: #595959;">Email </label>
                                {{form.email}}
                                {{form.email.errors}}
                                <div class="invalid-feedback">
                                    Your email is invalid
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="fullname">Full Name*</label>
                                {{form.full_name}}
                                {{form.full_name.errors}}
                                <div class="invalid-feedback">
                                    Your fullname is invalid
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="phone">Enter your phone number:</label> <br>
                  <img id="usa" src="{% static 'images/US.png' %}" alt="USA">
                  <p class="numb-1">+1 </p> 
                                  {{form.number}}
                                  {{form.number.errors}}
                              </div>
                              <div class="state"><label  for="sel1">State*</label>
                                {{form.state}}
                                {{form.state.errors}}
                
                
                            </div>
                            <div class="form-group d-none" id="buttons">
                                <p style="color: #595959;">Profile Picture</p><span
                                    class=" btn btn-primary btn-file upload">
                                    

                    Add photo{{form.profile_pic}}
                                    {{form.profile_pic.errors}}
                                    

                                </span>
                                <a href="" class="btn" id="delete" style="color: white;"> Delete</a>

                            </div>
                            <div class="form-group m-0">
                                <input type="submit" value="Save changes" class="save-btn btn  btn-primary btn-block">

                            </div>
                            <hr>
                            <a href="{% url 'account:log-out' %}"><p class="sign-btn   btn-block">Sign out</p></a>
                        </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

<!-- <section class="signin-section">
    <div class="container ">
        <div class="row justify-content-md-center">
            <div class="card-wrapper">

                <div class="card fat">
                    <h2 class="card-title " style="text-align: center;">Profile</h2>

                    <div class="card-body ">
                        <form method="POST" class="my-login-validation" novalidate="" action=""
                            enctype="multipart/form-data">
                            {% csrf_token %}
                            {{form.non_field_error}}

                            <div class="form-group">
                                <label for="email" style="color: #595959;">Email </label>
                                {{form.email}}
                                {{form.email.errors}}
                                <div class="invalid-feedback">
                                    Your email is invalid
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="fullname">Username*</label>
                                {{form.username}}
                                {{form.username.errors}}
                                <div class="invalid-feedback">
                                    Your fullname is invalid
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="fullname">Full Name*</label>
                                {{form.full_name}}
                                {{form.full_name.errors}}
                                <div class="invalid-feedback">
                                    Your fullname is invalid
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="phone">Enter your phone number:</label>
                                  {{form.number}}
                                  {{form.number.errors}}
                              </div>
                            <div class="form-group" id="buttons">
                                <p style="color: #595959;">Profile Picture</p> <span
                                    class=" btn btn-primary btn-file upload">
                                    Add photo{{form.profile_pic}}
                                    {{form.profile_pic.errors}}

                                </span>
                                <a href="" class="btn" id="delete" style="color: white;"> Delete</a>

                            </div>
                            <div class="form-group m-0">
                                <input type="submit" value="Save changes" class="save-btn btn  btn-primary btn-block">

                            </div>
                            <hr>
                            <a href="{% url 'account:log-out' %}"><p class="sign-btn  btn btn-primary btn-block">Sign out</p></a>
                        </form>
                        
                    </div>
                </div>

            </div>
        </div>
    </div>
</section> -->
{% endblock %}

{% block js %}
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/8.4.7/js/intlTelInput.js"></script>
{% endblock %}

account/templates/registration.html
{% extends 'base2.html' %}
{% load static %}

{% block title %} Register {% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/register.css' %}">
{% endblock %}


{% block content %}

    <section class="signin-section">
        <div class="container ">
            <div class="row justify-content-md-center">
                <div class="card-wrapper">

                    <div class="card fat">
                        <div class="card-body">
                            <h4 class="card-title " style="text-align: center;">Registration</h4>
                            <form method="POST" class="my-login-validation" novalidate="">


                                <div class="form-group m-0">
                                    <button type="button" class=" financial btn btn-primary btn-block">
                                        <a href="{% url 'account:advisor' %}"> As a Financial Planner</a>
                                    </button>
                                </div>

                                <div class="form-group m-0">
                                    <button type="button" class="advice btn btn-primary btn-block">
                                        <a href="{% url 'account:seeker' %}"> As an Advice seekers</a>
                                    </button>
                                </div>

                            </form>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>

{% endblock %}

account/templates/signin.html
{% extends 'base2.html' %}

{% load static %}

{% block title %}Sign In{% endblock %}

{% block css %}
<style>
    .container {
	 max-width: 80rem;
	 width: 100%;
	 height: auto;
	 padding: 0 2rem;
	 margin: 0 auto;
}
</style>
<link rel="stylesheet" href="{% static 'css/signin.css' %}">
{% endblock %}

{% block content %}
<section id="cover" class="min-vh-100">
    <div id="cover-caption">
        <div class="container">
            <div class="row text-white">
                <div class="col-lg-12 col-md-8 col-sm-10 mx-auto text-center form p-4">
                    <h1 class="display-4 py-2 text-truncate">Sign In</h1>
                    <div class="px-2">
                        <form method="POST" class="my-login-validation" novalidate="">
                            {% csrf_token %}
                            {{form.non_field_error}}
                            <!-- {{form.username}}
                            {{form.username.errors}} -->
                            
                            <div class="form-group">
                                <label for="email">Username </label>
                                {{form.username}}
                                {{form.username.errors}}
                                <div class="invalid-feedback">
                                    Your username is invalid
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="password">Password</label>
                                {{form.password}}
                                {{form.password.errors}}
                                <div class="invalid-feedback">
                                    Password is required
                                </div>
                            </div>



                            <div class="form-group m-0">
                                
                                <input class="btn btn-primary btn-block" type="submit" value="Sign In">
                            </div>
                            <p style="text-align: center; margin-top:21px;">
                                or
                            </p>
                            <div class="mt-4 text-center">
                                <a id="signup" href="{% url 'account:register' %}">Sign up</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>



{% endblock %}