account/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from account.views import MainLoginView,RegisterView,AdvisorView,SeekerView,ProfileView

app_name = 'account'

urlpatterns = [
    path('login/', MainLoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('register-advisor/', AdvisorView.as_view(), name='advisor'),
    path('register-seeker/', SeekerView.as_view(), name='seeker'),
    path('profile/<slug:slug>', ProfileView.as_view(), name='profile'),
    path('log-out', LogoutView.as_view(), name='log-out'),
]

core/urls.py
from django.urls import path

from .views import (
    HomePageView,
    CongratulationsPageView,
    MessageCongratulationsPageView,
    MatchedView,
    MessageAdvisorView
)

app_name = 'core'


urlpatterns = [
    path("", HomePageView.as_view(), name="index"),
    path("congratulations/", CongratulationsPageView.as_view(), name="congratulations"),
    path("message-congratulations/", MessageCongratulationsPageView.as_view(), name="message-congratulations"),
    path("matched-advisors/", MatchedView.as_view(), name="matched-advisors"),
    path("message-advisor/<slug:slug>", MessageAdvisorView.as_view(), name="message-advisor"),
]

fibility/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('account.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models


class AboutUsText(models.Model):
    text = models.TextField()
    added_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.text}'

    class Meta:
        verbose_name = 'About us text'
        verbose_name_plural = 'About us texts'

class MoreOnUsText(models.Model):
    text = models.TextField()
    added_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.text}'

    class Meta:
        verbose_name = 'More on us text'
        verbose_name_plural = 'More on us texts'

core/forms.py
from django import forms
from account.models import Message

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['subject', 'text']

        widgets = {
            'subject': forms.TextInput(attrs={'id': 'subject', 'placeholder': 'Your Subject', 'class': 'form-control'}),
            'text': forms.Textarea(attrs={'id': 'message', 'placeholder': 'Your Message', 'class': 'form-control', 'cols':'65', 'rows': '10'}),
        }

core/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView, DetailView
from .models import AboutUsText, MoreOnUsText
from account.models import User
from django.views.generic.edit import FormMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .forms import MessageForm

class HomePageView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['aboutus'] = AboutUsText.objects.order_by('-id').first
        context['moreonus'] = MoreOnUsText.objects.order_by('-id').first
        return context

class MatchedView(ListView):
    model = User
    context_object_name = "matched_advisors"
    template_name = "table.html"
    queryset = User.objects.filter(is_advisor=True).order_by('-id')[:1]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    # def get_queryset(self):
        
    #     print(queryset)

    #     return queryset

class MessageAdvisorView(FormMixin, DetailView):
    model = User
    context_object_name = "advisor"
    template_name = "message.html"
    form_class = MessageForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get_success_url(self):
        return reverse_lazy('core:message-congratulations')

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.sender = self.request.user
        form.instance.receiver = self.get_object()
        form.save()
        return super().form_valid(form)


class CongratulationsPageView(TemplateView):
    template_name = 'congratulation.html'


class MessageCongratulationsPageView(TemplateView):
    template_name = 'mcongratulation.html'

core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <title>{% block title %} {% endblock %}</title>

    <meta name="author" content="Kodinger">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Fibility">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="icon" href="{% static 'images/logo.png' %}" type="image/gif" sizes="4x4">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Mulish&display=swap" rel="stylesheet">
    <!-- Our Css -->
    <link rel="stylesheet" href="{% static 'css/global.css' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <link href="http://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css" rel="stylesheet">
        <script src="http://code.jquery.com/ui/1.12.0/jquery-ui.min.js" ></script>
        {% block css %}

    {% endblock %}
    <style>
        .profile-img {
    color: white;
    padding: 12px 35px;
    background-color: #162c9b;
    border: none;
}
    </style>
</head>

<body>
    <!-- Header Section Start -->
    {% include 'includes/header.html' %}
    <!-- Header Section End -->
    {% block content %}

    {% endblock %}
    <!-- Footer Start -->
    {% include 'includes/footer.html' %}
    <!--  Footer End -->
    <script src="{% static 'js/main.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
        integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
        crossorigin="anonymous"></script>

    {% block js %}

    {% endblock %}
</body>

</html>

core/templates/base2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <title>{% block title %} {% endblock %}</title>

    <meta name="author" content="Kodinger">
    <meta name="description" content="Fibility">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <link rel="icon" href="{% static 'images/logo.png' %}" type="image/gif" sizes="4x4">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Mulish&display=swap" rel="stylesheet">
    <!-- Our Css -->
    <link rel="stylesheet" href="{% static 'css/global.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <link href="http://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css" rel="stylesheet">
    <script src="http://code.jquery.com/ui/1.12.0/jquery-ui.min.js" ></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% block css %}

    {% endblock %}
    <style>
        .profile-img {
    color: white;
    padding: 12px 35px;
    background-color: #162c9b;
    border: none;
}
    </style>
</head>

<body class="my-login-page">
    <!-- Header Section Start -->
    {% include 'includes/header.html' %}
    <!-- Header Section End -->
    {% block content %}

    {% endblock %}
    <!-- Footer Start -->
    {% include 'includes/footer.html' %}
    <!--  Footer End -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
        integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/login.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

    {% block js %}

    {% endblock %}
</body>

</html>

core/templates/congratulation.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Congratulation{% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/congrats.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
  integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w=="
  crossorigin="anonymous" />
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">

{% endblock %}

{% block content %}
<section id="cover" class="min-vh-100">
  <div id="cover-caption">
      <div class="container">
          <div class="row text-white">
              <div class="col-xl-5 col-lg-12 col-md-8 col-sm-10 mx-auto text-center form p-4">
                  <h1 class="congrats" style="color: black;"> Congratulations</h1>
                  <div class="px-2">
                      <form action="" class="justify-content-center" style="margin-bottom: 20px;">
                          <img style="margin:auto" src="{% static 'images/Social Media.png' %}" alt="">
                          <div style="height: 71px;"></div>
                          <a href="{% url 'account:login' %}" style="text-decoration: none; margin-top: 71px !important; color: #162C9B
                        ; font-weight: bold; ">Search and match</a>
                      </form>
                  </div>
              </div>
          </div>
      </div>
  </div>
</section>
{% endblock %}

{% block js %}
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/8.4.7/js/intlTelInput.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
  integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
{% endblock %}

core/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/main.css' %}">
{% endblock %}

{% block title %} Fibility {% endblock %}

{% block content %}

<!-- Who we are section Start -->
<section id="whoWeare">
  <div class="container">
    <div class="row">
      <div class="col-md-6 left-w">
        <img width="100%" src="{% static 'images/Group.png' %}" alt="Group">
      </div>
      <div class="col-md-6 right-w">
        <h2>We Are Here For You</h2>
        <p>We help you make reasonable decisions when it <br> comes to spending money, not <br>
          irrational ones.
        </p>
        {% if request.user.is_authenticated %}
        {% if request.user.is_advisor == False  %}
        <a href="{% url 'core:matched-advisors' %}"
        style="max-width: 150px; height: 50px;  color: #162C9B; text-decoration: none; border: 1px solid #162C9B!important;"
        class="d-flex flex-row justify-content-center align-items-center border"><span
          style="margin-right: 10px;">Match</span>
        <img class="pl-2" width="" height="" src="{% static 'images/Group 251.png' %}" alt="arrow"></a>
        
        {% endif %}
        {% else %}
        <a href="{% url 'account:login' %}"
          style="max-width: 150px; height: 50px;  color: #162C9B; text-decoration: none; border: 1px solid #162C9B!important;"
          class="d-flex flex-row justify-content-center align-items-center border"><span
            style="margin-right: 10px;">Match</span>
          <img class="pl-2" width="" height="" src="{% static 'images/Group 251.png' %}" alt="arrow"></a>
        {% endif %}
        
      </div>
    </div>
  </div>
</section>
<!-- Who we are section End -->
<!-- About us Section Start -->
<section id="about-us">
  <div class="container">
    <div class="row">
      <div class="col-md-6 left-w about-left">
        <h2>About Us</h2>
        <p class="aboutus-text">{{aboutus.text}}
        </p>
      </div>
      <div class="col-md-6  about-right">
        <img width="100%" src="{% static 'images/Group 252.png' %}" alt="Group">

      </div>
    </div>
  </div>
</section>
<!-- About us Section End -->
<!-- Timeline section Start -->
<section id="time-l">
  <h3>
    How it works
  </h3>
  <p style="text-align: center;">We help the world’s leading organizations follow their shipping</p>
  <div class="timeline">
    <div class="container-t left">
      <div class="content">
        <div style="float: left;">
          <img class="time1" src="{% static 'images/one.png' %}" alt="Photo">
        </div>
        <div class="text-work" style="margin-top: 20px; margin-left: 120px;">
          <b style="color: #373F41;">Fill out five questions</b>
        </div>

      </div>
    </div>
    <div class="container-t right">
      <div class="content">
        <div style="float: left;">
          <img class="time1" src="{% static 'images/two.png' %}" alt="Photo">
        </div>
        <div class="text-work" style="margin-top: 20px; margin-left: 120px;">
          <b style="color: #373F41;">Get matched with an advisor</b>
        </div>

      </div>
    </div>
    <div class="container-t left">
      <div class="content">
        <div style="float: left;">
          <img class="time1" src="{% static 'images/three.png' %}" alt="Photo">
        </div>
        <div class="text-work" style="margin-top: 20px; margin-left: 120px;">
          <b style="color: #373F41;">Receive our services</b>
        </div>

      </div>
    </div>


  </div>

</section>
<!-- Timeline section End -->
<!-- More on us  section Start -->
<section class="more" id="moreonus">
  <div class="container">
    <div class="row">
      <div clas="col-12">
        <h2 id="more-on-us">Our why </h2>
        <p id="more-on-us-text">
          {{moreonus.text}}
        </p>
      </div>
    </div>
  </div>

</section>
<!-- More on us section End -->
{% endblock %}

core/templates/mcongratulation.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Congratulation{% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/congrats.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
  integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w=="
  crossorigin="anonymous" />
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">

{% endblock %}

{% block content %}
<section id="cover" class="min-vh-100">
  <div id="cover-caption">
      <div class="container">
          <div class="row text-white">
              <div class="col-xl-5 col-lg-12 col-md-8 col-sm-10 mx-auto text-center form p-4">
                  <h1 class="congrats" style="color: black;"> Congratulations</h1>
                  <div class="px-2">
                      <form action="" class="justify-content-center" style="margin-bottom: 20px;">
                          <div style="height: 71px;">
                          <h4 style="color: black;">Your message is sent to Advisor!</h4>
                          </div>
                          <a href="{% url 'core:index' %}" style="text-decoration: none; margin-top: 71px !important; color: #162C9B
                        ; font-weight: bold; ">Go back</a>
                      </form>
                  </div>
              </div>
          </div>
      </div>
  </div>
</section>
{% endblock %}

{% block js %}
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/8.4.7/js/intlTelInput.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
  integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
{% endblock %}

core/templates/table.html
{% extends 'base2.html' %}
{% load static %}

{% block title %} Financial Register {% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/table.css' %}">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
{% endblock %}

{% block content %}
<body class="my-login-page">

    <section id="cover" class="min-vh-100">
          
            <div class="container">
                <div class="row text-white">

                    <div class="col-12">
                 <form action="{% url 'core:matched-advisors' %}" method="GET" style="display: flex;">
                    <p style=" color: #737B7D; margin-top: 17px; margin-right: 5px;">Your annual salary range 0-100k :</p>
         <input class="btn apply" type="submit" value="Apply" style="margin-left: 5px; width: 200px;">
                </form>
                    </div>
                    {%if matched_advisors.count == 0%}
                    <h1 style="color: black;">No results</h1>
                    {% endif %}
                    {% for advisor in matched_advisors %}
                    {% if advisor.state == request.user.state %}
                    <div class="col-md-6 col-xs-12" style="margin-top: 44px;">
                        <div class="card p-3">
                            <div class="d-flex align-items-center">
                                <div class="image"> <img src="" class="rounded" width="51"> </div>
                                <div class="ml-3 w-100">
                                    <h4 class="mb-0 mt-0" style="color: #737B7D; text-align: left; font-size: 18px!important;">{{ advisor.full_name }}</h4>
                                    <div class=" mt-2 d-flex justify-content-between rounded text-white ">
                                        <p class="card-text"
                                style="width:109px; text-align:left; display: inline-block; background-color: #9ff0cb; color: #16613f ;">
                            </p>
                            <a href="{% url 'core:message-advisor' advisor.slug %}">Contact me</a>
                                    </div>
                                  
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                 
                  
                </div>
            </div>
    </section>


    <!-- <section id="cover" class="min-vh-100">
          
            <div class="container">
                <div class="row text-white">

                    <div class="col-12">
                        <h1 style="margin-bottom: 64px; text-align: left; color: black;">Your match results</h1>
                        <form action="{% url 'core:matched-advisors' %}" method="GET">
                            <p style="display: inline-block; color: #737B7D;">Your annual salary range 0-100k :</p>
                 <input class="form-control" type="text" name="salary" placeholder="${{request.user.salary}}" value="{{request.GET.salary}}">
                 <input class="btn apply" type="submit" value="Apply">
                        </form>
                 
                    </div>
                    {% for advisor in matched_advisors %}
                    {% if advisor.state == request.user.state %}
                    <div class="col-md-6 col-xs-12" style="margin-bottom:27px; margin-top: 44px;">
                        <div class="card p-3">
                            <div class="d-flex align-items-center">
                                <div class="image"> <img src="" class="rounded" width="51"> </div>
                                <div class="ml-3 w-100">
                                    <h4 class="mb-0 mt-0" style="color: black; text-align: left;">{{ advisor.full_name }}</h4>
                                    <div class="p-2 mt-2 d-flex justify-content-between rounded text-white ">
                                        <p class="card-text"
                                style="width:95px; text-align:left; display: inline-block; background-color: #9ff0cb; color: #6BCAA0 ;">
                                ${{ advisor.salary }}
                            </p>
                            <a href="{% url 'core:message-advisor' advisor.slug %}">Contact with me</a>
                                    </div>
                                  
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                    
                  
                </div>
            </div>
    </section> -->
    <!-- <section class="signin-section">
    <div class="container ">
      <div class="row justify-content-md-center">
        <div class="card-wrapper">
          <div class="card fat">
            <h2 class="card-title " style="text-align: center;">Advice seekers</h2>
            <div class="card-body">
              <form method="POST" class="my-login-validation" novalidate="">
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section> -->
    <!-- Footer Start -->
    <!--  Footer End -->

    <!--  Footer End -->
    <script>

        function isOlderEdgeOrIE() {
            return (
                window.navigator.userAgent.indexOf("MSIE ") > -1 ||
                !!navigator.userAgent.match(/Trident.*rv\:11\./) ||
                window.navigator.userAgent.indexOf("Edge") > -1
            );
        }

        function valueTotalRatio(value, min, max) {
            return ((value - min) / (max - min)).toFixed(2);
        }

        function getLinearGradientCSS(ratio, leftColor, rightColor) {
            return [
                '-webkit-gradient(',
                'linear, ',
                'left top, ',
                'right top, ',
                'color-stop(' + ratio + ', ' + leftColor + '), ',
                'color-stop(' + ratio + ', ' + rightColor + ')',
                ')'
            ].join('');
        }

        function updateRangeEl(rangeEl) {
            var ratio = valueTotalRatio(rangeEl.value, rangeEl.min, rangeEl.max);

            rangeEl.style.backgroundImage = getLinearGradientCSS(ratio, '#ff5126', '#eeeeee');
        }

        function initRangeEl() {
            var rangeEl = document.querySelector('input[type=range]');
            var textEl = document.querySelector('input[type=text]');

            /**
             * IE/Older Edge FIX
             * On IE/Older Edge the height of the <input type="range" />
             * is the whole element as oposed to Chrome/Moz
             * where the height is applied to the track.
             *
             */
            if (isOlderEdgeOrIE()) {
                rangeEl.style.height = "20px";
                // IE 11/10 fires change instead of input
                // https://stackoverflow.com/a/50887531/3528132
                rangeEl.addEventListener("change", function (e) {
                    textEl.value = e.target.value;
                });
                rangeEl.addEventListener("input", function (e) {
                    textEl.value = e.target.value;
                });
            } else {
                updateRangeEl(rangeEl);
                rangeEl.addEventListener("input", function (e) {
                    updateRangeEl(e.target);
                    textEl.value = e.target.value;
                });
            }
        }

        initRangeEl();


        var slider = document.getElementById("myRange");
        var output = document.getElementById("demo");
        output.innerHTML = slider.value;

        slider.oninput = function () {
            output.innerHTML = this.value;
        }

    </script>

    <script src="./assets/js/main.js"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <script src="/assets/js/login.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

    <script>
        //       $("input[type=range]").mousemove(function (e) {
        //     var val = ($(this).val() - $(this).attr('min')) / ($(this).attr('max') - $(this).attr('min'));
        //     var percent = val * 100;

        //     $(this).css('background-image',
        //         '-webkit-gradient(linear, left top, right top, ' +
        //         'color-stop(' + percent + '%, #ff5126), ' +
        //         'color-stop(' + percent + '%, #eeeeee)' +
        //         ')');

        //     $(this).css('background-image',
        //         '-moz-linear-gradient(left center, #ff5126 0%, #ff5126 ' + percent + '%, #eeeeee ' + percent + '%, #eeeeee 100%)');
        // }); 

        var slider = document.getElementById("myRange");
        var output = document.getElementById("demo");
        output.innerHTML = slider.value;

        slider.oninput = function () {
            output.innerHTML = this.value;
        }


    </script>

</body>
{% endblock %}

</html>